# Generated by Django 5.0 on 2024-01-25 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_marks_dashboard_subtasks_title_alter_card_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='color',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='font_color',
        ),
        migrations.RemoveField(
            model_name='marks',
            name='mark_text',
        ),
        migrations.AddField(
            model_name='marks',
            name='marks_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
