# Generated by Django 5.0 on 2024-01-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_marks_color_remove_marks_font_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='marks_array',
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_color', models.CharField(default='#000000')),
                ('color', models.CharField(blank=True, null=True)),
                ('mark_text', models.CharField(blank=True, max_length=255, null=True)),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_marks', to='boards.marks')),
            ],
        ),
    ]
