# Generated by Django 5.0 on 2024-01-25 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_marks_marks_array_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='marks',
            new_name='parent_marks',
        ),
    ]
